debug = true

[subscribe]
event_types = ["MoveEvent", "Publish", "CoinBalanceChange", "TransferObject", "NewObject", "EpochChange", "Checkpoint"]

[bots]

[bots.discord]
token = "discord bot token"

[database]
# https://gorm.io/docs/connecting_to_the_database.html
driver = "sqlite3"
dsn = "db.sqlite3"
