debug = true

[subscribe]
event_types = ["MoveEvent", "Publish", "CoinBalanceChange", "TransferObject", "NewObject", "EpochChange", "Checkpoint"]

[bots]

[bots.discord]
token = "discord bot token"

[database]
[database.postgres]
url = "postgres://dbadmin:password@localhost:5432/db"